build: avoid compiler error on temporary in doc string formatting
Resolves an issue seen on 1.84.x with the following error:

    error[E0716]: temporary value dropped while borrowed
    --> src/lib.rs:802:22

The latest `rustc` knows this usage was valid and does not complain,
but a let-binding was added to work around it to support older
versions.

Updates crate version to 0.1.7